/* Generated by updater/update.mjs. Fallback for opening index.html directly from disk. */
window.JOBS_DATA = {
 "meta": {
  "schemaVersion": 1,
  "generator": "updater/update.mjs — rule-based keyword matching, no AI",
  "lastUpdated": null,
  "lastAttempt": null,
  "nextUpdate": null,
  "updateIntervalDays": 7,
  "schedule": "Mondays at 10:00 UTC (6:00 am Toronto in summer, 5:00 am in winter)",
  "counts": {
   "active": 0,
   "new": 0,
   "high": 0,
   "employers": 0,
   "closed": 0,
   "expired": 0
  }
 },
 "sources": [
  {
   "id": "adzuna",
   "name": "Adzuna (aggregates Canadian job boards and employer sites)",
   "kind": "aggregator",
   "status": "pending",
   "count": 0,
   "message": "Waiting for the first weekly run",
   "lastSuccess": null
  },
  {
   "id": "jooble",
   "name": "Jooble (aggregates Canadian job boards)",
   "kind": "aggregator",
   "status": "pending",
   "count": 0,
   "message": "Waiting for the first weekly run",
   "lastSuccess": null
  },
  {
   "id": "workday-example",
   "name": "Employer careers (Workday) — replace with a real employer",
   "kind": "employer",
   "status": "disabled",
   "count": 0,
   "message": "Turned off in updater/sources.json",
   "lastSuccess": null
  },
  {
   "id": "greenhouse-example",
   "name": "Employer careers (Greenhouse) — replace with a real employer",
   "kind": "employer",
   "status": "disabled",
   "count": 0,
   "message": "Turned off in updater/sources.json",
   "lastSuccess": null
  },
  {
   "id": "lever-example",
   "name": "Employer careers (Lever) — replace with a real employer",
   "kind": "employer",
   "status": "disabled",
   "count": 0,
   "message": "Turned off in updater/sources.json",
   "lastSuccess": null
  },
  {
   "id": "smartrecruiters-example",
   "name": "Employer careers (SmartRecruiters) — replace with a real employer",
   "kind": "employer",
   "status": "disabled",
   "count": 0,
   "message": "Turned off in updater/sources.json",
   "lastSuccess": null
  },
  {
   "id": "rss-example",
   "name": "Any RSS job feed — paste a feed URL",
   "kind": "board",
   "status": "disabled",
   "count": 0,
   "message": "Turned off in updater/sources.json",
   "lastSuccess": null
  },
  {
   "id": "jsonld-example",
   "name": "Employer job pages with structured data (schema.org JobPosting)",
   "kind": "employer",
   "status": "disabled",
   "count": 0,
   "message": "Turned off in updater/sources.json",
   "lastSuccess": null
  }
 ],
 "jobs": []
};
